language: php
php:
  - 5.6
  - 7.0
  - 7.1
sudo: false
services:
  - memcached
before_install:
  - phpenv config-rm xdebug.ini
  - phpenv config-add tests/config.ini
install:
  - composer install
script:
  - vendor/bin/phpunit
